### ISSUE TITLE
Number of Transformer layers 

### ISSUE THREAD

**Issue by IwasakiYuuki** [graykode/ALBERT-Pytorch#3]
Thank you for implementation of ALBERT by pytorch.
I have a question about the model construction.
https://github.com/graykode/ALBERT-Pytorch/blob/7cac1770ab155b5aa7cafd0b1854503cd58915cc/pretrain.py#L198
Why is the number of transformer layers one ?
Is this correct ?

**Comment by graykode** [comment]
Please see https://github.com/graykode/ALBERT-Pytorch/blob/7cac1770ab155b5aa7cafd0b1854503cd58915cc/models.py#L175
I hope this code hell you, Thanks

**Comment by IwasakiYuuki** [comment]
sorry, i missed it...
Thank you for answering to my question.
